# Generated by Django 5.2.5 on 2025-11-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_paciente_idx_estado_activo_and_more'),
        ('triage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='tipo',
            field=models.CharField(choices=[('enfermero', 'Enfermero Triajero'), ('medico', 'Médico'), ('administrador', 'Administrador')], default='enfermero', max_length=15, verbose_name='Tipo de Profesional'),
        ),
        migrations.AddIndex(
            model_name='signosvitales',
            index=models.Index(fields=['fecha_hora', 'nivel_urgencia'], name='idx_fecha_nivel'),
        ),
        migrations.AddIndex(
            model_name='signosvitales',
            index=models.Index(fields=['nivel_urgencia', 'paciente'], name='idx_triage_critico'),
        ),
    ]
