# Generated by Django 5.2.5 on 2025-10-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signosvitales',
            name='nivel_conciencia',
            field=models.CharField(choices=[('A', 'Alerta y orientado'), ('V', 'Responde a estímulos verbales'), ('P', 'Responde solo a estímulos dolorosos'), ('U', 'No responde (inconsciente)')], help_text='Escala AVPU', max_length=1, verbose_name='Nivel de Conciencia'),
        ),
        migrations.AlterField(
            model_name='triageresult',
            name='news_score',
            field=models.PositiveIntegerField(help_text='Puntaje calculado del National Early Warning Score', verbose_name='Puntaje NEWS'),
        ),
        migrations.AlterField(
            model_name='triageresult',
            name='nivel_urgencia',
            field=models.CharField(choices=[('VERDE', 'Verde - Sin riesgo vital (atención dentro de 60 minutos)'), ('AMARILLO', 'Amarillo - Riesgo moderado (atención dentro de 30 minutos)'), ('ROJO', 'Rojo - Riesgo vital inmediato (atención inmediata)')], max_length=8, verbose_name='Nivel de Urgencia'),
        ),
    ]
