# Generated by Django 5.2.5 on 2026-08-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_paciente_profesional_atencion'),
        ('triage', '0002_alter_profesional_tipo_signosvitales_idx_fecha_nivel_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='signosvitales',
            index=models.Index(fields=['paciente', 'nivel_urgencia', '-fecha_hora'], name='idx_pac_nivel_fecha'),
        ),
        migrations.AddIndex(
            model_name='signosvitales',
            index=models.Index(fields=['profesional', 'fecha_hora', 'nivel_urgencia'], name='idx_prof_fecha_nivel'),
        ),
    ]
