# Generated by Django 4.2.11 on 2025-10-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0002_alter_signosvitales_nivel_conciencia_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='signosvitales',
            index=models.Index(fields=['-fecha_hora'], name='idx_signos_fecha'),
        ),
        migrations.AddIndex(
            model_name='signosvitales',
            index=models.Index(fields=['paciente', '-fecha_hora'], name='idx_paciente_fecha'),
        ),
        migrations.AddIndex(
            model_name='triageresult',
            index=models.Index(fields=['nivel_urgencia', '-fecha_calculo'], name='idx_urgencia_fecha'),
        ),
        migrations.AddIndex(
            model_name='triageresult',
            index=models.Index(fields=['-fecha_calculo'], name='idx_triage_fecha'),
        ),
    ]
