# Generated by Django 4.2.11 on 2025-10-13 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('triage', '0003_signosvitales_idx_signos_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signosvitales',
            name='enfermero',
        ),
        migrations.AddField(
            model_name='signosvitales',
            name='profesional',
            field=models.ForeignKey(default=1, help_text='Profesional (médico/enfermero) que registró los signos vitales', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Profesional'),
            preserve_default=False,
        ),
    ]
