# Generated by Django 4.2.11 on 2025-10-13 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('triage', '0004_remove_signosvitales_enfermero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(help_text='Documento Nacional de Identidad (sin puntos)', max_length=8, unique=True, verbose_name='DNI')),
                ('tipo', models.CharField(choices=[('medico', 'Médico'), ('enfermero', 'Enfermero')], max_length=10, verbose_name='Tipo de Profesional')),
                ('matricula', models.CharField(blank=True, help_text='Número de matrícula profesional', max_length=20, verbose_name='Matrícula Profesional')),
                ('activo', models.BooleanField(default=True, help_text='Si el profesional puede acceder al sistema', verbose_name='Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Profesional',
                'verbose_name_plural': 'Profesionales',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
