# Generated by Django 4.2.11 on 2025-10-13 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0005_add_profesional_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signosvitales',
            name='profesional',
            field=models.ForeignKey(help_text='Profesional (médico/enfermero) que registró los signos vitales', on_delete=django.db.models.deletion.PROTECT, to='triage.profesional', verbose_name='Profesional'),
        ),
    ]
