# Generated by Django 4.2.11 on 2025-10-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0006_update_profesional_field'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='profesional',
            index=models.Index(fields=['dni'], name='idx_profesional_dni'),
        ),
        migrations.AddIndex(
            model_name='profesional',
            index=models.Index(fields=['activo', 'tipo'], name='idx_profesional_activo_tipo'),
        ),
    ]
