# Generated by Django 4.2.11 on 2025-10-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0007_optimize_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='signosvitales',
            index=models.Index(fields=['profesional', '-fecha_hora'], name='idx_profesional_fecha'),
        ),
    ]
