# Generated by Django 5.2.5 on 2025-10-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0008_ultra_optimize'),
    ]

    operations = [
        # Agregar campos de triage a SignosVitales
        migrations.AddField(
            model_name='signosvitales',
            name='news_score',
            field=models.PositiveIntegerField(blank=True, help_text='Puntaje calculado del National Early Warning Score', null=True, verbose_name='Puntaje NEWS'),
        ),
        migrations.AddField(
            model_name='signosvitales',
            name='nivel_urgencia',
            field=models.CharField(blank=True, choices=[('VERDE', 'Verde - Sin riesgo vital (atención dentro de 60 minutos)'), ('AMARILLO', 'Amarillo - Riesgo moderado (atención dentro de 30 minutos)'), ('ROJO', 'Rojo - Riesgo vital inmediato (atención inmediata)')], max_length=8, null=True, verbose_name='Nivel de Urgencia'),
        ),
        migrations.AddField(
            model_name='signosvitales',
            name='tiempo_atencion_max',
            field=models.PositiveIntegerField(blank=True, help_text='Tiempo máximo de espera en minutos', null=True, verbose_name='Tiempo máximo de atención'),
        ),
        # Eliminar modelo TriageResult
        migrations.DeleteModel(
            name='TriageResult',
        ),
    ]
