# Generated by Django 5.2.5 on 2025-10-13 16:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaEvolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.TextField(help_text='Descripción del estado actual o cambios observados en el paciente', verbose_name='Nota de evolución')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now, help_text='Momento en que se registró la nota', verbose_name='Fecha y Hora')),
                ('importante', models.BooleanField(default=False, help_text='Marcar si la nota requiere atención especial', verbose_name='Nota importante')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_evolucion', to='patients.paciente', verbose_name='Paciente')),
                ('profesional', models.ForeignKey(help_text='Profesional que registró la nota de evolución', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Profesional')),
            ],
            options={
                'verbose_name': 'Nota de Evolución',
                'verbose_name_plural': 'Notas de Evolución',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
