# Generated by Django 4.2.11 on 2025-10-13 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evolution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notaevolucion',
            name='profesional',
            field=models.ForeignKey(help_text='Profesional médico (médico/enfermero) que registró la nota de evolución', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Profesional'),
        ),
    ]
