# Generated by Django 5.2.5 on 2025-10-13 16:04

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del paciente', max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(help_text='Apellido del paciente', max_length=100, verbose_name='Apellido')),
                ('dni', models.CharField(help_text='Documento Nacional de Identidad (sin puntos ni espacios)', max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='El DNI debe tener entre 7 y 8 dígitos.', regex='^\\d{7,8}$')], verbose_name='DNI')),
                ('edad', models.PositiveIntegerField(help_text='Edad del paciente en años', verbose_name='Edad')),
                ('motivo_consulta', models.TextField(help_text='Descripción del motivo por el cual consulta el paciente', verbose_name='Motivo de consulta')),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en que el paciente ingresó al sistema', verbose_name='Fecha de ingreso')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el paciente está actualmente en el sistema', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['-fecha_ingreso'],
            },
        ),
    ]
