# Generated by Django 5.2.5 on 2025-10-22 22:51

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, help_text='Nombre del paciente (opcional para pacientes inconscientes)', max_length=100, null=True, verbose_name='Nombre')),
                ('apellido', models.CharField(blank=True, help_text='Apellido del paciente (opcional para pacientes inconscientes)', max_length=100, null=True, verbose_name='Apellido')),
                ('dni', models.CharField(blank=True, help_text='Documento Nacional de Identidad (opcional para pacientes inconscientes)', max_length=8, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='El DNI debe tener entre 7 y 8 dígitos.', regex='^\\d{7,8}$')], verbose_name='DNI')),
                ('edad', models.PositiveIntegerField(blank=True, help_text='Edad del paciente en años (opcional para pacientes inconscientes)', null=True, verbose_name='Edad')),
                ('motivo_consulta', models.TextField(help_text='Descripción del motivo por el cual consulta el paciente', verbose_name='Motivo de consulta')),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en que el paciente ingresó al sistema', verbose_name='Fecha de ingreso')),
                ('estado_atencion', models.CharField(choices=[('ESPERANDO', '⏳ Esperando atención'), ('EN_ATENCION', '👩\u200d⚕️ En atención'), ('ATENDIDO', '✅ Atendido'), ('DERIVADO', '🏥 Derivado')], default='ESPERANDO', help_text='Estado actual del paciente en el proceso de atención', max_length=12, verbose_name='Estado de Atención')),
                ('fecha_atencion', models.DateTimeField(blank=True, help_text='Momento en que fue atendido el paciente', null=True, verbose_name='Fecha de Atención')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el paciente está actualmente en el sistema', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['-fecha_ingreso'],
                'indexes': [models.Index(fields=['activo', 'estado_atencion', '-fecha_ingreso'], name='idx_pacientes_activos'), models.Index(fields=['dni'], name='idx_pacientes_dni'), models.Index(fields=['fecha_ingreso'], name='idx_pacientes_fecha')],
            },
        ),
    ]
