# Generated by Django 4.2.11 on 2025-10-13 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='apellido',
            field=models.CharField(blank=True, help_text='Apellido del paciente (opcional para pacientes inconscientes)', max_length=100, null=True, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='dni',
            field=models.CharField(blank=True, help_text='Documento Nacional de Identidad (opcional para pacientes inconscientes)', max_length=8, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='El DNI debe tener entre 7 y 8 dígitos.', regex='^\\d{7,8}$')], verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='edad',
            field=models.PositiveIntegerField(blank=True, help_text='Edad del paciente en años (opcional para pacientes inconscientes)', null=True, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(blank=True, help_text='Nombre del paciente (opcional para pacientes inconscientes)', max_length=100, null=True, verbose_name='Nombre'),
        ),
    ]
