# Generated by Django 5.2.5 on 2025-11-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['activo', 'estado_atencion'], name='idx_estado_activo'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['edad'], name='idx_pacientes_edad'),
        ),
    ]
