# Generated by Django 5.2.5 on 2025-11-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_paciente_idx_estado_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='estado_atencion',
            field=models.CharField(choices=[('ESPERANDO', '⏳ Esperando atención'), ('EN_ATENCION', '👩\u200d⚕️ En atención'), ('PASE_A_SALA', '🏥 Pase a Sala'), ('ALTA', '✅ Alta'), ('PASE_A_UTI', '🚨 Pase a UTI'), ('DERIVADO', '🏥 Derivado')], default='ESPERANDO', help_text='Estado actual del paciente en el proceso de atención', max_length=12, verbose_name='Estado de Atención'),
        ),
    ]
