# Generated by Django 4.2.11 on 2025-10-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_paciente_apellido_alter_paciente_dni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='estado_atencion',
            field=models.CharField(choices=[('ESPERANDO', '⏳ Esperando atención'), ('EN_ATENCION', '👩\u200d⚕️ En atención'), ('ATENDIDO', '✅ Atendido'), ('DERIVADO', '🏥 Derivado')], default='ESPERANDO', help_text='Estado actual del paciente en el proceso de atención', max_length=12, verbose_name='Estado de Atención'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_atencion',
            field=models.DateTimeField(blank=True, help_text='Momento en que fue atendido el paciente', null=True, verbose_name='Fecha de Atención'),
        ),
    ]
