# Generated by Django 5.2.5 on 2025-11-10 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_paciente_estado_atencion'),
        ('triage', '0002_alter_profesional_tipo_signosvitales_idx_fecha_nivel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='profesional_atencion',
            field=models.ForeignKey(blank=True, help_text='Profesional que marcó al paciente como atendido', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_atendidos', to='triage.profesional', verbose_name='Profesional que Atendió'),
        ),
    ]
