# Generated by Django 5.2.5 on 2025-10-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_estado_atencion'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['activo', 'estado_atencion', '-fecha_ingreso'], name='idx_pacientes_activos'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['dni'], name='idx_pacientes_dni'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['fecha_ingreso'], name='idx_pacientes_fecha'),
        ),
    ]
